# Generated by Django 4.0.3 on 2022-03-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('check_in', models.CharField(max_length=200)),
                ('check_out', models.CharField(max_length=200)),
            ],
        ),
    ]
